spring:
  elasticsearch:
    bboss:
#      elasticUser: elastic
#      elasticPassword: changeme
      elasticsearch:
        rest:
          hostNames: 172.168.1.109:9200,172.168.1.108:9200,192.168.0.208:9200
          ##hostNames: 172.168.1.109:9200,172.168.1.108:9200 ##集群地址配置
#        dateFormat: yyyy.MM.dd
#        timeZone: Asia/Shanghai
#        ttl: 2d
        showTemplate: true
#        discoverHost: false
#      dslfile:
#        refreshInterval: -1
#      http:
#        timeoutConnection: 5000
#        timeoutSocket: 5000
#        connectionRequestTimeout: 5000
#        retryTime: 1
#        maxLineLength: -1
#        maxHeaderCount: 200
#        maxTotal: 400
#        defaultMaxPerRoute: 200
#        soReuseAddress: false
#        soKeepAlive: false
#        timeToLive: 3600000
#        keepAlive: 3600000
#        keystore:
#        keyPassword:
#        hostnameVerifier:
server:
  port: 8888
